function buat_login(){
  var tukar = document.getElementById('x');
  tukar.parentElement.removeChild(tukar);
  var text_Login = document.createElement("P");
  text_Login.innerHTML = "Silakan Mendaftar!";
  text_Login.className = "tulisan_login";
  var element1 = document.getElementsByTagName('div')[0];
  element1.appendChild(text_Login);
  var form = document.createElement("FORM");
  element1.appendChild(form);
  var label1 = document.createElement("label");
  label1.innerHTML = "Nama User";
  form.appendChild(label1);
  var inputNamaUser = document.createElement("input");
  inputNamaUser.type = "text";
  inputNamaUser.className = "form_login";
  inputNamaUser.name = "NamaUser";
  inputNamaUser.placeholder = "Nama User..";
  form.appendChild(inputNamaUser);
  var label2 = document.createElement("label");
  label2.innerHTML = "Nomor Handphone";
  form.appendChild(label2);
  var nomorHandphone = document.createElement("input");
  nomorHandphone.type = "tel";
  nomorHandphone.className = "form_login";
  nomorHandphone.name = "NamaUser";
  nomorHandphone.placeholder = "Nomor Handphone.";
  form.appendChild(nomorHandphone);
  var label3 = document.createElement("label");
  label3.innerHTML = "Username";
  form.appendChild(label3);
  var input_username = document.createElement("input");
  input_username.type = "text";
  input_username.className = "form_login";
  input_username.name = "username";
  input_username.placeholder = "username atau email..";
  form.appendChild(input_username);
  var label4 = document.createElement("label");
  label4.innerHTML = "Password";
  form.appendChild(label4);
  var input_password = document.createElement("input");
  input_password.type = "password";
  input_password.className = "form_login";
  input_password.name = "password";
  input_password.placeholder = "password..";
  form.appendChild(input_password);
  var tombolSubmit = document.createElement('input');
  tombolSubmit.type = "submit";
  tombolSubmit.className = "tombol_login";
  form.appendChild(tombolSubmit);
}
